---
title: "Code for zoo data for **Female contraception and male castration increase lifespan across vertebrates**"
subtitle: "**Supplmentary Material**"
author: "**Michael Garratt, Malgorzata Lagisz, Johanna Stärk, Christine Neyt, Michael Stout, José V. V. Isola, Veronica Cowl, Nannette Driver-Ruiz, Ashley D. Franklin, Monica M. McDonald, Katelyn Mucha, David Powell, Rachel Thompson, Susan L. Walker, Jean-Michel Gaillard, Dalia A. Conde, Jean-François Lemaître, Fernando Colchero and Shinichi Nakagawa**"
date: "`r Sys.Date()`"
format:
  html:
    toc: true
    toc-location: left
    toc-depth: 3
    toc-title: "**Table of Contents**"
    output-file: "zoo.html"
    theme: simplex
    embed-resources: true
    code-fold: true
    code-tools: true
    number-sections: true
    #bibliography: ./bib/ref.bib
    fontsize: "12"
    max-width: "10"
    code-overflow: wrap
crossref: 
  fig-title: Figure     # (default is "Figure")
  tbl-title: Table     # (default is "Table")
  title-delim: —     # (default is ":")
  fig-prefix: Fig.   # (default is "Figure")
  tbl-prefix: Tab.    # (default is "Table")
editor_options: 
  chunk_output_type: console
execute:
  warning: false
  message: false
  tidy: true
  #cache: true
---

## Setting up

### Loading packages

```{r}

# loading
pacman::p_load(tidyverse,
               metafor,
               pander,
               stringr,
               ape,
               here,
               kableExtra,
               patchwork,
               lme4,
               readxl,
               #metaAidR,
               rotl,
               orchaRd,
               emmeans,
               clubSandwich,
               png,
               grid,
               here,
               cowplot,
               apextra,
               ggimage,
               ggstance,
               ggtree
)

```

### Loading data

```{r}
# main data
dat0 <- read_csv(here("data", "zoo", "zoo.csv"), na = c("", "NA"))

# phylogeny
tree <- read.tree( here("data", "zoo", "tree_zoo.tre"))

# taxonomy
tax <- read.csv(here("data", "zoo", "vertlife_taxonomy_translation_table.csv"))

dat0 %>% left_join(tax, by = c("species" = "zims.species")) -> dat_full

# talking out species with no data (Pseudocheirus peregrinus = likely to be mistaks in data)
dat_full %>% filter(species != "Chrysocyon brachyurus" &
                    species != "Crocuta crocuta" &
                    species != "Neofelis nebulosa" &
                    species != "Panthera uncia" &
                    species != "Pseudocheirus peregrinus") %>% 
  mutate(phylogeny = gsub(" ", "_", vertlife.species)) -> dat

# adding Cervus canadensis
dat$vertlife.species[which(dat$species == "Cervus canadensis")] <-"Cervus canadensis"
dat$phylogeny[which(dat$species == "Cervus canadensis")] <-"Cervus_canadensis"

# fixing species name
dat$species[dat$species == "Equus asinus"] <- "Equus_africanus"
dat$species[dat$species == "Aonyx cinereus"] <- "Aonyx cinerea"
dat$species[dat$species == "Bubalus bubalis"] <- "Bubalus arnee"


# life span data 
to_drop <-
  tree$tip.label[which(!(tree$tip.label %in% unique(dat$phylogeny)))]

tree <- drop.tip(tree, to_drop)
length(tree$tip.label)

tree <- as.ultrametric(tree)

#tree <- compute.brlen(tree)
cor_tree <- vcv(tree, corr = TRUE)

# length(unique(dat$species))
# length(unique(dat$phylogeny))
# 
# match(unique(gsub(" ","_", dat$species)), unique(dat$phylogeny))
# match(unique(dat$phylogeny), unique(gsub(" ","_", dat$species)))

```

### Custom functions

We have 7 custom functions named : `cont_gen()`,`get_pred1()`, `get_pred2()`, `mr_results()`, `all_models()`,`folded_mu`, and `folded_v`, all of which are used later and the code is included here.

```{r}
# custom functions

#' Title: Contrast name generator
#'
#' @param name: a vector of character strings
cont_gen <- function(name) {
  combination <- combn(name, 2)
  name_dat <- t(combination)
  names <- paste(name_dat[, 1], name_dat[, 2], sep = "-")
  return(names)
}

#' @title get_pred1: intercept-less model
#' @description Function to get CIs (confidence intervals) and PIs (prediction intervals) from rma objects (metafor)
#' @param model: rma.mv object 
#' @param mod: the name of a moderator 
get_pred1 <- function (model, mod = " ") {
  name <- firstup(as.character(stringr::str_replace(row.names(model$beta), mod, "")))
  len <- length(name)
  
   if (len != 1) {
        newdata <- diag(len)
        pred <- metafor::predict.rma(model, 
                                     newmods = newdata,
                                     tau2.levels = 1:len)
    }
    else {
        pred <- metafor::predict.rma(model)
  }
  estimate <- pred$pred
  lowerCL <- pred$ci.lb
  upperCL <- pred$ci.ub 
  lowerPR <- pred$cr.lb
  upperPR <- pred$cr.ub 
  
  table <- tibble(name = factor(name, levels = name, labels = name), estimate = estimate,
                  lowerCL = lowerCL, upperCL = upperCL,
                  pval = model$pval,
                  lowerPR = lowerPR, upperPR = upperPR)
}

#' @title get_pred2: normal model
#' @description Function to get CIs (confidence intervals) and PIs (prediction intervals) from rma objects (metafor)
#' @param model: rma.mv object 
#' @param mod: the name of a moderator 
get_pred2 <- function (model, mod = " ") {
  name <- as.factor(str_replace(row.names(model$beta), 
                                paste0("relevel", "\\(", mod,", ref = name","\\)"),""))
  len <- length(name)
  
  if(len != 1){
  newdata <- diag(len)
  pred <- predict.rma(model, intercept = FALSE, newmods = newdata[ ,-1])
  }
  else {
    pred <- predict.rma(model)
  }
  estimate <- pred$pred
  lowerCL <- pred$ci.lb
  upperCL <- pred$ci.ub 
  lowerPR <- pred$cr.lb
  upperPR <- pred$cr.ub 
  
  table <- tibble(name = factor(name, levels = name, labels = name), estimate = estimate,
                  lowerCL = lowerCL, upperCL = upperCL,
                  pval = model$pval,
                  lowerPR = lowerPR, upperPR = upperPR)
}

#' @title mr_results
#' @description Function to put results of meta-regression and its contrasts
#' @param res1: data frame 1
#' @param res1: data frame 2
mr_results <- function(res1, res2) {
  restuls <-tibble(
    `Fixed effect` = c(as.character(res1$name), cont_gen(res1$name)),
    Estimate = c(res1$estimate, res2$estimate),
    `Lower CI [0.025]` = c(res1$lowerCL, res2$lowerCL),
    `Upper CI  [0.975]` = c(res1$upperCL, res2$upperCL),
    `P value` = c(res1$pval, res2$pval),
    `Lower PI [0.025]` = c(res1$lowerPR, res2$lowerPR),
    `Upper PI  [0.975]` = c(res1$upperPR, res2$upperPR),
  )
}


#' @title all_models
#' @description Function to take all possible models and get their results
#' @param model: intercept-less model
#' @param mod: the name of a moderator 

all_models <- function(model, mod = " ", type = "homo") {
  
  # getting the level names out
  level_names <- levels(factor(model$data[[mod]]))
  dat2 <- model$data
  mod <- mod


  run_rma1 <- function(name) {
      VCV1 <- vcalc(vi = dat2$vi,
             cluster = dat2$vertlife.species,
             rho = 0.5)
    rma.mv(yi, V = VCV1,
                   mods = ~relevel(dat2[[mod]], ref = name),
                     random = list(
                       ~1|vertlife.species,
                       ~1|phylogeny,
                       ~1|obs_id),
                     R = list(phylogeny = cor_tree),
                     data = dat2,
                     control = list(optimizer = "Nelder-Mead"))
   }

    run_rma2 <- function(name) {
    
            VCVa <- vcalc(abs_vi, vertlife.species, 
                    rho = 0.5, data = dat2)
               
               rma.mv(abs_yi, V = VCVa,
               mods = ~relevel(dat2[[mod]], ref = name),
                     random = list(
                       ~1|vertlife.species,
                       ~1|phylogeny,
                       ~1|obs_id),
                     R = list(phylogeny = cor_tree),
                     data = dat2,
                     control = list(optimizer = "Nelder-Mead"))
   }

# results of meta-regression including all contrast results; taking the last level out ([-length(level_names)])
# this does not work for hetero model?
if (type == "homo"){

    model_all <- purrr::map(level_names[-length(level_names)], run_rma1)

  } else {
  model_all <- purrr::map(level_names[-length(level_names)], run_rma2)
  }
  
  # getting estimates from intercept-less models (means for all the groups)
  res1 <- get_pred1(model, mod = mod)
  
  # getting estiamtes from all contrast models
  res2_pre <- purrr::map(model_all, ~ get_pred2(.x, mod = mod))
  
  # a list of the numbers to take out unnecessary contrasts
  contra_list <- Map(seq, from=1, to=1:(length(level_names) - 1))
  res2 <- purrr::map2_dfr(res2_pre, contra_list, ~.x[-(.y), ]) 
  # creating a table
  res_tab <- mr_results(res1, res2) %>% 
  kable("html",  digits = 3) %>%
  kable_styling("striped", position = "left") %>%
  scroll_box(width = "100%")
  
  # results
  res_tab

}


##########
# functions for absolute values


# folded mean
folded_mu <-function(mean, variance){
  mu <- mean
  sigma <- sqrt(variance)
  fold_mu <- sigma*sqrt(2/pi)*exp((-mu^2)/(2*sigma^2)) + mu*(1 - 2*pnorm(-mu/sigma))
  fold_mu
} 

# folded variance
folded_v <-function(mean, variance){
  mu <- mean
  sigma <- sqrt(variance)
  fold_mu <- sigma*sqrt(2/pi)*exp((-mu^2)/(2*sigma^2)) + mu*(1 - 2*pnorm(-mu/sigma))
  fold_se <- sqrt(mu^2 + sigma^2 - fold_mu^2)
  # adding se to make bigger mean
  fold_v <-fold_se^2
  fold_v
} 

```

### Preparing data set (calulating effect sizes)

```{r}
##############################################
# data sets comparing normal vs. contraception 
##############################################

# male surgical

dat_m_surg <- dat %>% filter(is.na(Male_Surgical_Mean) == FALSE, is.na(Male_None_Mean) == FALSE) %>% 
  mutate(M_control_m = Male_None_Mean,
         M_control_sd = sqrt(Male.None)*Male_None_SE,
         M_control_n = Male.None,
         M_surgical_m = Male_Surgical_Mean,
         M_surgical_sd = sqrt(Male.Surgical)*Male_Surgical_SE,
         M_surgical_n = Male.Surgical,
         sex = "male",
         type = "surgical")

dat_m_surg <- escalc("ROM", 
              m1i = M_surgical_m,
              m2i = M_control_m,
              sd1i = M_surgical_sd,
              sd2i = M_control_sd,
              n1i = M_surgical_n,
              n2i = M_control_n,
              data = dat_m_surg,
              )

#  male hormonal
dat_m_horm <- dat %>% filter(is.na(Male_Hormonal_Mean) == FALSE, is.na(Male_None_Mean) == FALSE) %>% 
  mutate(M_control_m = Male_None_Mean,
         M_control_sd = sqrt(Male.None)*Male_None_SE,
         M_control_n = Male.None,
         M_hormonal_m = Male_Hormonal_Mean,
         M_hormonal_sd = sqrt(Male.Hormonal)*Male_Hormonal_SE,
         M_hormonal_n = Male.Hormonal,
         sex = "male",
         type = "hormonal")

dat_m_horm <- escalc("ROM", 
                     m1i = M_hormonal_m,
                     m2i = M_control_m,
                     sd1i = M_hormonal_sd,
                     sd2i = M_control_sd,
                     n1i = M_hormonal_n,
                     n2i = M_control_n,
                     data = dat_m_horm,
)

# male immunological
dat_m_immu <- dat %>% filter(is.na(Male_Immunological_Mean) == FALSE, 
    is.na(Male_None_Mean) == FALSE) %>%
  mutate(M_control_m = Male_None_Mean,
         M_control_sd = sqrt(Male.None)*Male_None_SE,
         M_control_n = Male.None,
         M_immunol_m = Male_Immunological_Mean,
         M_immunol_sd = sqrt(Male.Immunological)*Male_Immunological_SE,
         M_immunol_n = Male.Immunological,
         sex = "male",
         type = "immunological")

dat_m_immu <- escalc("ROM", 
                     m1i = M_immunol_m,
                     m2i = M_control_m,
                     sd1i = M_immunol_sd,
                     sd2i = M_control_sd,
                     n1i = M_immunol_n,
                     n2i = M_control_n,
                     data = dat_m_immu,
)


# female hormonal data 

dat_f_horm <- dat %>% filter(is.na(Female_Hormonal_Mean) == FALSE, is.na(Female_None_Mean) == FALSE) %>% 
  mutate(F_control_m = Female_None_Mean,
         F_control_sd = sqrt(Female.None)*Female_None_SE,
         F_control_n = Female.None,
         F_hormonal_m = Female_Hormonal_Mean,
         F_hormonal_sd = sqrt(Female.Hormonal)*Female_Hormonal_SE,
         F_hormonal_n = Female.Hormonal,
         sex = "female",
         type = "hormonal")

dat_f_horm <- escalc("ROM", 
                     m1i = F_hormonal_m,
                     m2i = F_control_m,
                     sd1i = F_hormonal_sd,
                     sd2i = F_control_sd,
                     n1i = F_hormonal_n,
                     n2i = F_control_n,
                     data = dat_f_horm,
)

# female surgical data

dat_f_surg<- dat %>% filter(is.na(Female_Surgical_Mean) == FALSE, is.na(Female_None_Mean) == FALSE) %>% 
  mutate(F_control_m = Female_None_Mean,
         F_control_sd = sqrt(Female.None)*Female_None_SE,
         F_control_n = Female.None,
         F_surgical_m = Female_Surgical_Mean,
         F_surgical_sd = sqrt(Female.Surgical)*Female_Surgical_SE,
         F_surgical_n = Female.Surgical,
         sex = "female",
         type = "surgical")


dat_f_surg <- escalc("ROM", 
                     m1i = F_surgical_m,
                     m2i = F_control_m,
                     sd1i = F_surgical_sd,
                     sd2i = F_control_sd,
                     n1i = F_surgical_n,
                     n2i = F_control_n,
                     data = dat_f_surg,
)

# female immunological
dat_f_immu <- dat %>% filter(is.na(Female_Immunological_Mean) == FALSE, 
    is.na(Female_None_Mean) == FALSE) %>%
  mutate(F_control_m = Female_None_Mean,
         F_control_sd = sqrt(Female.None)*Female_None_SE,
         F_control_n = Female.None,
         F_immunol_m = Female_Immunological_Mean,
         F_immunol_sd = sqrt(Female.Immunological)*Female_Immunological_SE,
         F_immunol_n = Female.Immunological,
         sex = "female",
         type = "immunological")

dat_f_immu <- escalc("ROM", 
                     m1i = F_immunol_m,
                     m2i = F_control_m,
                     sd1i = F_immunol_sd,
                     sd2i = F_control_sd,
                     n1i = F_immunol_n,
                     n2i = F_control_n,
                     data = dat_f_immu,
)


rbind(
dat_m_horm[ , c(1, 53, 55, 62:65)], # 1
dat_m_surg[ , c(1, 53, 55, 62:65)], # 2
dat_f_horm[ , c(1, 53, 55, 62:65)], # 3 
dat_f_surg[ , c(1, 53, 55, 62:65)], # 4
dat_m_immu[ , c(1, 53, 55, 62:65)], # 5
dat_f_immu[ , c(1, 53, 55, 62:65)] # 6
) -> dat_all

# observation id
dat_all$obs_id <- factor(1:nrow(dat_all))

# sex type combined
dat_all %>% mutate(sex_type = paste(sex, type, sep = "_")) -> dat_all

######################################
# data sets looking at sex differences
######################################

# female normal vs. male surgical (1)

dat_fm_ns <- dat %>% filter(is.na(Female_None_Mean) == FALSE, 
                            is.na(Male_Surgical_Mean) == FALSE) %>% 
  transmute(F_normal_m = Male_None_Mean,
         F_normal_sd = sqrt(Female.None)*Female_None_SE,
         F_normal_n = Female.None,
         M_surgical_m = Male_Surgical_Mean,
         M_surgical_sd = sqrt(Male.Surgical)*Male_Surgical_SE,
         M_surgical_n = Male.Surgical,
         species = species,
         phylogeny = phylogeny,
         category = "F normal/M surgical"
         )

dat_fm_ns <- escalc("ROM", 
              m1i = F_normal_m,
              m2i = M_surgical_m,
              sd1i = F_normal_sd,
              sd2i = M_surgical_sd,
              n1i = F_normal_n,
              n2i = M_surgical_n,
              data = dat_fm_ns,
              )

# female hormonal vs. male normal (2)

dat_fm_hn <- dat %>% filter(is.na(Female_Hormonal_Mean) == FALSE, 
                            is.na(Male_None_Mean) == FALSE) %>% 
  transmute(F_hormonal_m = Female_Hormonal_Mean,
         F_hormonal_sd = sqrt(Female.Hormonal*Female_Hormonal_SE),
         F_hormonal_n = Female.Hormonal,
         M_normal_m = Male_None_Mean,
         M_normal_sd = sqrt(Male.None)*Male_None_SE,
         M_normal_n = Male.None,
         species = species,
         phylogeny = phylogeny,
         category = "F hormonal/M normal"
         )

dat_fm_hn <- escalc("ROM", 
              m1i = F_hormonal_m,
              m2i = M_normal_m,
              sd1i = F_hormonal_sd,
              sd2i = M_normal_sd,
              n1i = F_hormonal_n,
              n2i = M_normal_m,
              data = dat_fm_hn,
              )



# female surgical vs. male normal (3)

dat_fm_sn <- dat %>% filter(is.na(Female_Surgical_Mean) == FALSE,
                            is.na(Male_None_Mean) == FALSE) %>%
  transmute(F_surgical_m = Female_Surgical_Mean,
         F_surgical_sd = sqrt(Female.Surgical*Female_Surgical_SE),
         F_surgical_n = Female.Surgical,
         M_normal_m = Male_None_Mean,
         M_normal_sd = sqrt(Male.None)*Male_None_SE,
         M_normal_n = Male.None,
         species = species,
         phylogeny = phylogeny,
         category = "F hormonal/M normal"
         )

dat_fm_sn <- escalc("ROM", 
              m1i = F_surgical_m,
              m2i = M_normal_m,
              sd1i = F_surgical_sd,
              sd2i = M_normal_sd,
              n1i = F_surgical_n,
              n2i = M_normal_n,
              data = dat_fm_sn,
              )


# female surgical vs. male surgical (4)

dat_fm_ss <- dat %>% filter(is.na(Female_Surgical_Mean) == FALSE, 
                            is.na(Male_Surgical_Mean) == FALSE) %>% 
    transmute(F_surgical_m = Female_Surgical_Mean,
                 F_surgical_sd = sqrt(Female.Surgical*Female_Surgical_SE),
                 F_surgical_n = Female.Surgical,
                 M_surgical_m = Male_Surgical_Mean,
                 M_surgical_sd = sqrt(Male.Surgical)*Male_Surgical_SE,
                 M_surgical_n = Male.Surgical,
                 species = species,
                 phylogeny = phylogeny,
                 category = "F surgical/M surgical"
                 )

dat_fm_ss <- escalc("ROM", 
                            m1i = F_surgical_m,
                            m2i = M_surgical_m,
                            sd1i = F_surgical_sd,
                            sd2i = M_surgical_sd,
                            n1i = F_surgical_n,
                            n2i = M_surgical_n,
                            data = dat_fm_ss,
                            )

# female normal vs. male normal (5)

dat_fm_nn <- dat %>% filter(is.na(Female_None_Mean) == FALSE, 
                                                        is.na(Male_None_Mean) == FALSE) %>% 
    transmute(F_normal_m = Female_None_Mean,
                 F_normal_sd = sqrt(Female.None*Female_None_SE),
                 F_normal_n = Female.None,
                 M_normal_m = Male_None_Mean,
                 M_normal_sd = sqrt(Male.None*Male_None_SE),
                 M_normal_n = Male.None,
                 species = species,
                 phylogeny = phylogeny,
                 category = "F normal/M normal"
                 )

dat_fm_nn <- escalc("ROM", 
                            m1i = F_normal_m,
                            m2i = M_normal_m,
                            sd1i = F_normal_sd,
                            sd2i = M_normal_sd,
                            n1i = F_normal_n,
                            n2i = M_normal_n,
                            data = dat_fm_nn,
                            )

# female normal vs. male hormonal (6)

dat_fm_nh <- dat %>% filter(is.na(Female_None_Mean) == FALSE,
                            is.na(Male_Hormonal_Mean) == FALSE) %>%
  transmute(F_normal_m = Female_None_Mean,
            F_normal_sd = sqrt(Female.None*Female_None_SE),
            F_normal_n = Female.None,
            M_hornomal_m = Male_Hormonal_Mean,
            M_hornomal_sd = sqrt(Male.Hormonal)*Male_Hormonal_SE,
            M_hornomal_n = Male.Hormonal,
            species = species,
            phylogeny = phylogeny,
            category = "F normal/M hornomal"
  )

dat_fm_nh <- escalc("ROM", 
                    m1i = F_normal_m,
                    m2i = M_hornomal_m,
                    sd1i = F_normal_sd,
                    sd2i = M_hornomal_sd,
                    n1i = F_normal_n,
                    n2i = M_hornomal_n,
                    data = dat_fm_nh,
)

# female normal vs. male immunological (7)

dat_fm_ni <- dat %>% filter(is.na(Female_None_Mean) == FALSE,
                            is.na(Male_Immunological_Mean) == FALSE) %>%
  transmute(F_normal_m = Female_None_Mean,
            F_normal_sd = sqrt(Female.None*Female_None_SE),
            F_normal_n = Female.None,
            M_immunological_m = Male_Immunological_Mean,
            M_immunological_sd = sqrt(Male.Immunological)*Male_Immunological_SE,
            M_immunological_n = Male.Immunological,
            species = species,
            phylogeny = phylogeny,
            category = "F normal/M immunological"
  )
        
dat_fm_ni <- escalc("ROM", 
                    m1i = F_normal_m,
                    m2i = M_immunological_m,
                    sd1i = F_normal_sd,
                    sd2i = M_immunological_sd,
                    n1i = F_normal_n,
                    n2i = M_immunological_n,
                    data = dat_fm_ni,
)

# female immunological vs. male normal (8)

dat_fm_in <- dat %>% filter(is.na(Female_Immunological_Mean) == FALSE,
                            is.na(Male_None_Mean) == FALSE) %>%
  transmute(F_immunological_m = Female_Immunological_Mean,
            F_immunological_sd = sqrt(Female.Immunological*Female_Immunological_SE),
            F_immunological_n = Female.Immunological,
            M_normal_m = Male_None_Mean,
            M_normal_sd = sqrt(Male.None)*Male_None_SE,
            M_normal_n = Male.None,
            species = species,
            phylogeny = phylogeny,
            category = "F immunological/M normal"
  )

dat_fm_in <- escalc("ROM", 
                    m1i = F_immunological_m,
                    m2i = M_normal_m,
                    sd1i = F_immunological_sd,
                    sd2i = M_normal_sd,
                    n1i = F_immunological_n,
                    n2i = M_normal_n,
                    data = dat_fm_in,
)


# female hormonal vs. male hormonal (9)

dat_fm_hh <- dat %>% filter(is.na(Female_Hormonal_Mean) == FALSE,
                            is.na(Male_Hormonal_Mean) == FALSE) %>%
  transmute(F_hornomal_m = Female_Hormonal_Mean,
            F_hornomal_sd = sqrt(Female.Hormonal*Female_Hormonal_SE),
            F_hornomal_n = Female.Hormonal,
            M_hornomal_m = Male_Hormonal_Mean,
            M_hornomal_sd = sqrt(Male.Hormonal)*Male_Hormonal_SE,
            M_hornomal_n = Male.Hormonal,
            species = species,
            phylogeny = phylogeny,
            category = "F hornomal/M hornomal"
  )
     
dat_fm_hh <- escalc("ROM", 
                    m1i = F_hornomal_m,
                    m2i = M_hornomal_m,
                    sd1i = F_hornomal_sd,
                    sd2i = M_hornomal_sd,
                    n1i = F_hornomal_n,
                    n2i = M_hornomal_n,
                    data = dat_fm_hh,
)


# female immunological vs. male immunological (10)

dat_fm_ii <- dat %>% filter(is.na(Female_Immunological_Mean) == FALSE,
                    is.na(Male_Immunological_Mean) == FALSE) %>%
  transmute(F_immunological_m = Female_Immunological_Mean,
            F_immunological_sd = sqrt(Female.Immunological*Female_Immunological_SE),
            F_immunological_n = Female.None,
            M_immunological_m = Male_Immunological_Mean,
            M_immunological_sd = sqrt(Male.Immunological)*Male_Immunological_SE,
            M_immunological_n = Male.Immunological,
            species = species,
            phylogeny = phylogeny,
            category = "F immunological/M immunological"
  )

dat_fm_ii <- escalc("ROM", 
                    m1i = F_immunological_m,
                    m2i = M_immunological_m,
                    sd1i = F_immunological_sd,
                    sd2i = M_immunological_sd,
                    n1i = F_immunological_n,
                    n2i = M_immunological_n,
                    data = dat_fm_ii,
)

rbind(
  dat_fm_ns[ , 7:12], # 1
  dat_fm_hn[ , 7:12], # 2 
  dat_fm_sn[ , 7:12], # 3
  dat_fm_ss[ , 7:12], # 4
  dat_fm_nn[ , 7:12],  # 5
  dat_fm_nh[ , 7:12],  # 6
  dat_fm_ni[ , 7:12],  # 7
  dat_fm_in[ , 7:12], # 8
  dat_fm_hh[ , 7:12], # 9
  dat_fm_ii[ , 7:12]  # 10
) -> dat_comb


dat_comb$obs_id <- factor(1:nrow(dat_comb))

# adding category
dat_comb$contraception <- factor(dat_comb$category, levels = c("F immunological/M immunological",
                                                           "F hornomal/M hornomal",
                                                           "F surgical/M surgical",
                                                           "F immunological/M normal",
                                                           "F hormonal/M normal",  
                                                           "F surgical/M normal",
                                                           "F normal/M immunological",
                                                           "F normal/M hormonal",
                                                           "F normal/M surgical",
                                                           "F normal/M normal"),
                                                labels = c("F contraception/M contraception",
                                                           "F contraception/M contraception",
                                                           "F contraception/M contraception",
                                                           "F contraception/M normal",
                                                           "F contraception/M normal",  
                                                           "F contraception/M normal",
                                                           "F normal/M contraception",
                                                           "F normal/M contraception",
                                                           "F normal/M contraception",
                                                           "F normal/M normal"),
                             
)

# absolute values
dat_comb <- dat_comb %>% mutate(
  abs_yi = abs(yi), # we use this one (conservative)
  abs_yi2 = folded_mu(yi, vi), # alternative way
  abs_vi = folded_v(yi, vi))

```


